### PR TITLE
Don't remove corpses after alt+f4 while unconscious

### PR DESCRIPTION
**Pull request by IvanMMM**

### CODE REVIEW

**Comment by micovery** [comment]
Looks good ... just a couple of requests. Can you turn this whole block: 

https://github.com/IvanMMM/ArmA3_Wasteland.Altis/blob/9098d43b05716d151978fb45a801c4cc97c84c25/server/functions/fn_onPlayerDisconnected.sqf#L18-L51

Into a separate function. Maybe put it in shFunctions.sqf ... could call it `sh_drop_player_inventory`.

After moving it over there change the tabs back to spaces.

**Comment by IvanMMM** [comment]
Here you go :) Tested, working

**Comment by micovery** [comment]
Awesome, thanks! One last thing. In the code that drops the player inventory, can you add definitions for local variables:

```
private["_player", "_money"];

private["_m"];

private["_inventory", "_id", "_qty",  "_type", "_object"];

```

Note that I've put them in separate sections, put each one nearest to the block/section where it's used, as opposed to defining them all in one shot at the top.

The reason why I like to put them near where they are used is because it makes it easier to track unused local variables as the code evolves. Unlike full-fledged languages like Java, there is not one IDE for SQF that would detect un-used local variables.

**Comment by IvanMMM** [comment]
Sure, np. But one question. Why do we need this code? What is it supposed to do? 
I understand when we need to get some value that is set at forEach (ie). But in another ways?

**Comment by micovery** [comment]
The "private" definitions ensure locality of the variable. If you don't define the variables before using, you'd be re-using (or worse overwriting) the variable that was defined with the same name at higher level in the stack of function calls. That's when you get weird bugs ... and have no idea why something is being overwritten. So it's a must to always define local variables before using them.

**Comment by IvanMMM** [comment]
Done :) But isn't the "_" prefix tells arma that this variable is local?

**Comment by micovery** [comment]
It does, and it does not ... SQF being such a :hankey:  language, it will let you overwrite/re-use local variables that were defined in a parent scope.

Try something like this:

``` sqf
child = {
  _a = _a + 1;
};

parent = {
  private["_a"];
  _a = 0;
  diag_log format["_a = %1, before calling child", _a];
  call child;
  diag_log format["_a = %1, after calling child", _a];
};

call parent;

```

**Pull request merged**
