### PR TITLE
Added option to allow UAV control only for owner.

### PR DESCRIPTION
**Pull request by IvanMMM**

### CODE REVIEW

**Comment by micovery** [comment]
Very nice. Got some feedback. Can you make it an addon (in its own directory inside addons). I know it's not a lot of code, but lets follow the addon strategy in order to minimize the changes to the vanilla files. Also,  instead of making it sleep for 0.1 ... maybe 0.5, or even 1 second, that way it'd be less demanding on the client-side.

**Comment by IvanMMM** [comment]
Sure. I'l make 0.5 then. Tested, it works fine. Don't want to give players enough time to start engines :)

**Comment by IvanMMM** [comment]
Well, found one issue. If player is fast enough and will manage to click on UAV driver/gunner camera, he will gain control of UAV anyway. We can decrease check time or add check "if in UAV slot", but can't say I know how to add it. player / vehicle player while in UAV still returns usual values. And what's even more important, won't additional check undo the profit of using 0.5? Another way we could do it is force close UAV connection GUI. But in this case it could be a problem selecting correct uav in 10+ list.

**Comment by micovery** [comment]
Merged manually through 6540c8138a0e955163f29d03ba9991f29eeebba3

**Pull request closed without merging**
